In [2]:
import numpy as np
from hmmlearn import hmm

In [9]:
Y= np.array([[1,1,0,1,0,0,1,0,1,0,1,1,1,1,0,1,0,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,2,1,1,1,1,1,2,1,1,2,1,2,2,2,2,1,2,1,2,1,2,1,1,1,1,1,2,2,1,1,1,1,1,0,1,1,1,1,1,1,0,0,0,1,1,1,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,1,2,1,1,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,2,1,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,1,1,1,1,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,2,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,0,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,1,1,1,2,2,2,2,2,2,1,1,2,1,2,1,2,1,2,3,3,0,3,1,1,1,1,1,2,1,2,3,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,3,0,3,2,1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]]).T
X = np.array([[5, 4, 4, 3, 3, 3, 5, 5, 5, 5, 4, 5, 5, 6, 5, 6, 5, 7, 5, 6, 3, 4, 3, 6, 5, 5, 4, 5, 5, 5, 1, 6, 5, 1, 5, 6, 5, 5, 5, 5, 3, 5, 5, 6, 6, 6, 7, 6, 7, 7, 6, 7, 5, 5, 6, 6, 5, 6, 5, 4, 5, 5, 6, 5, 5, 7, 5, 6, 6, 6, 6, 6, 5, 6, 7, 7, 3, 4, 5, 4, 2, 2, 2, 5, 6, 6, 2, 3, 4, 3, 1, 2, 3, 1, 4, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 3, 4, 4, 3, 4, 5, 5, 4, 4, 2, 2, 2, 3, 2, 2, 3, 1, 2, 4, 3, 3, 2, 2, 3, 3, 4, 2, 4, 3, 3, 4, 3, 3, 2, 2, 1, 2, 1, 2, 3, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 3, 2, 2, 3, 3, 3, 3, 3, 2, 2, 3, 2, 3, 2, 2, 3, 3, 2, 3, 2, 2, 4, 1, 3, 2, 2, 4, 3, 3, 3, 1, 4, 4, 4, 4, 3, 4, 3, 4, 4, 4, 4, 4, 3, 3, 4, 1, 3, 4, 4, 4, 3, 4, 3, 4, 5, 3, 3, 3, 3, 4, 4, 4, 5, 3, 4, 4, 4, 4, 4, 4, 4, 3, 4, 3, 4, 3, 2, 3, 4, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 4, 3, 3, 2, 3, 2, 4, 3, 3, 3, 4, 4, 3, 3, 4, 5, 4, 4, 4, 4, 3, 3, 2, 3, 3, 3, 4, 3, 3, 2, 2, 3, 3, 3, 3, 2, 2, 2, 2, 3, 2, 3, 3, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 1, 2, 2, 3, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 3, 2, 2, 3, 3, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 3, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 1, 2, 3, 5, 4, 4, 4, 4, 4, 4, 3, 3, 3, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 3, 1, 3, 1, 3, 2, 2, 1, 2, 2, 2, 1, 1, 2, 4, 3, 3, 2, 3, 2, 2, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 4, 3, 2, 1, 2, 3, 3, 1, 3, 1, 3, 1, 0, 5, 5, 4, 5, 6, 5, 7, 6, 5, 5, 7, 5, 5, 4, 2, 1, 2, 4, 2, 2, 1, 2, 1, 1, 5, 5, 5, 2, 2, 3, 2, 2, 2, 2, 1, 1, 2, 2, 2, 4, 2, 4, 6, 7, 6, 5, 7, 7, 5, 6, 6, 5, 7, 6, 5, 6, 2, 3, 2, 3, 3, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 0, 3, 2, 2, 1, 1, 1, 2, 2, 3, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 3, 2, 2, 3, 3, 3, 3, 2, 2, 3, 3, 1, 1, 5, 5, 3, 5, 4, 5, 3, 4, 3, 4, 3, 3, 3, 3, 1, 4, 3, 3, 1, 1, 2, 2, 1, 3, 4, 5, 3, 4, 3, 3, 3, 4, 4, 3, 4, 4, 3, 3, 3, 3, 3, 2, 3, 4, 2, 4, 4, 1, 4, 1, 2, 3, 3, 4, 4, 4, 2, 2, 4, 2, 3, 2, 4, 4, 3, 4, 4, 3, 4, 4, 4, 2, 3, 3, 4, 4, 4, 4, 4, 5, 4, 4, 5, 4, 4, 5, 5, 5, 5, 4, 5, 4, 5, 3, 4, 5, 5, 4, 5, 5, 4, 4, 4, 5, 5, 4, 3, 4, 3, 4, 4, 4, 4, 2, 4, 5, 3, 4, 5, 3, 5, 5, 5, 4, 3, 4, 3, 5, 4, 4, 4, 5, 3, 4, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 1, 4, 4, 5, 4, 4, 5, 5, 4, 4, 3, 5, 5, 4, 5, 5, 3, 4, 5, 5, 5, 4, 4, 4, 5, 5, 3, 3, 2, 5, 3, 3, 2, 4, 4, 4, 1, 5, 5, 5, 6, 5, 4, 3, 3, 3, 5, 4, 4, 5, 6, 5, 2, 5, 6, 6, 3, 5, 2, 1, 4, 4, 3, 4, 3, 4, 4, 2, 2, 3, 3, 3, 2, 1, 2, 1, 4, 4, 3, 1, 4, 2, 2, 3, 1, 2, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 2, 3, 3, 3, 4, 5, 5, 4, 6, 6, 5, 1, 1, 0, 2, 2, 2, 2, 1, 1, 5, 6, 6, 7, 6, 6, 5, 7, 6, 6, 5, 5, 5, 5, 5, 3, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 3, 2, 2, 1, 1, 1, 1, 2, 2, 1, 0, 0, 1, 0, 1, 2, 1, 2, 3, 3, 2, 2, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 3, 2, 3, 3, 3, 4, 4, 4, 5, 5, 4, 5, 5, 5, 5, 4, 4, 3, 3, 4, 5, 5, 3, 5, 5, 4, 5, 5, 5, 3, 5, 5, 5, 1, 5, 3, 5, 5, 5, 4, 5, 6, 5, 5, 4, 6, 6, 5, 5, 4, 4, 4, 5, 5, 5, 4, 3, 4, 3, 5, 4, 5, 5, 5, 4, 5, 5, 6, 6, 5, 5, 5, 4, 5, 4, 5, 4, 4, 5, 4, 5, 4, 4, 3, 2, 3, 4, 2, 3, 5, 2, 5, 2, 6, 5, 5, 5, 4, 3, 3, 4, 4, 4, 4, 3, 4, 4, 2, 5, 5, 4, 4, 4, 5, 5, 2, 3, 4, 4, 4, 5, 3, 5, 5, 2, 6, 5, 5, 5, 5, 5, 4, 5, 5, 5, 2, 4, 5, 4, 3, 5, 4, 5, 6, 5, 5, 5, 4, 5, 4, 5, 5, 6, 5, 6, 4, 5, 5, 5, 5, 5, 4, 5, 4, 5, 5, 2, 5, 3, 4, 4, 4, 3, 3, 5, 5, 5, 4, 4, 5, 4, 4, 3, 5, 4, 4, 3, 3, 4, 2, 4, 4, 3, 4, 3, 5, 4, 3, 4, 2, 5, 2, 4, 3, 4, 2, 2, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 3, 3, 3, 2, 2, 2, 3, 3, 2, 3, 3, 3, 3, 4, 2, 3, 2, 4, 3, 3, 5, 4, 4, 4, 5, 4, 4, 5, 4, 5, 3, 4, 5, 4, 4, 5, 4, 5, 4, 4, 5, 4, 4, 4, 4, 4, 2, 2, 5, 2, 5, 3, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 3, 3, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 4, 4, 5, 3, 4, 3, 3, 4, 4, 3, 3, 3, 2, 4, 1, 4, 2, 3, 4, 3, 3, 4, 2, 3, 4, 4, 3, 3, 3, 3, 3, 3, 4, 4, 5, 6, 5, 4, 5, 5, 3, 5, 3, 2, 4, 4, 4, 2, 4, 3, 5, 4, 4, 2, 2, 4, 1, 4, 2, 4, 2, 4, 1, 4, 2, 3, 1, 3, 3, 3, 1, 3, 2, 2, 2, 2, 2, 1, 2, 2, 2, 3, 3, 3, 3, 2, 3, 3, 4, 3, 4, 3, 3, 4, 4, 1, 4, 4, 2, 4, 4, 5, 4, 4, 2, 3, 4, 3, 3, 3, 3, 2, 4, 3, 2, 3, 2, 3, 1, 3, 1, 2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 3, 1, 3, 4, 1, 3, 3, 1, 3, 2, 2, 1, 3, 1, 2, 3, 1, 2, 1, 2, 3, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 1, 3, 2, 2, 2, 3, 3, 4, 1, 3, 2, 4, 2, 3, 4, 3, 3, 2, 3, 2, 2, 2, 2, 1, 5, 3, 3, 3, 3, 3, 3, 4, 1, 3, 3, 4, 3, 3, 2, 4, 4, 1, 4, 3, 2, 2, 2, 3, 4, 3, 3, 3, 2, 4, 2, 2, 2, 4, 4, 3, 4, 4, 4, 4, 5, 3, 4, 4, 4, 5, 5, 3, 3, 3, 2, 4, 3, 4, 2, 3, 3, 3, 4, 2, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 3, 4, 3, 4, 5, 4, 4, 2, 1, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 3, 3, 4, 4, 4, 3, 4, 4, 4, 4, 4, 3, 3, 5, 3, 4, 3, 4, 5, 5, 4, 3, 4, 5, 4, 5, 5, 5, 4, 4, 4, 4, 5, 4, 3, 4, 4, 3, 4, 4, 3, 5, 1, 4, 3, 3, 4, 4, 4, 3, 4, 4, 4, 5, 4, 4, 3, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 5, 4, 5, 4, 4, 4, 4, 5, 4, 4, 3, 5, 4, 4, 4, 4, 1, 3, 4, 2, 5, 4, 5, 2, 4, 3, 4, 3, 3, 2, 3, 3, 4, 2, 2, 4, 2, 2, 3, 4, 3, 3, 3, 4, 4, 4, 4, 5, 4, 4, 5, 4, 4, 4, 5, 5, 3, 5, 3, 4, 4, 5, 4, 4, 4, 5, 4, 4, 4, 3, 5, 3, 3, 2, 2, 3, 3, 3, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 4, 3, 1, 2, 3, 2, 2, 2, 1, 2, 2, 2, 1, 3, 2, 3, 4, 3, 2, 2, 2, 4, 3, 4, 4, 4, 2, 3, 3, 3, 4, 3, 4, 4, 4, 2, 4, 4, 3, 4, 3, 2, 3, 2, 3, 3, 3, 4, 3, 2, 3, 4, 4, 4, 3, 5, 4, 4, 5, 4, 1, 3, 3, 2, 4, 5, 5, 5, 5, 5, 4, 5, 4, 5, 4, 5, 5, 5, 1, 5, 4, 4, 4, 3, 4, 3, 4, 5, 3, 4, 5, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 4, 4, 2, 4, 5, 4, 5, 3, 2, 0, 2, 1, 3, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 3, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 1, 2, 3, 2, 2, 2, 3, 3, 3, 2, 3, 3, 1, 2, 1, 1, 2, 2, 2, 2, 2, 3, 3, 2, 2, 1, 1, 1, 2, 2, 3, 3, 2, 3, 4, 3, 3, 3, 3, 4, 2, 4, 3, 3, 2, 3, 3, 4, 4, 4, 3, 4, 3, 4, 4, 3, 3, 2, 4, 3, 1, 3, 1, 2, 2, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 3, 2, 1, 3, 2, 3, 3, 3, 2, 2, 2, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 1, 2, 3, 3, 4, 3, 3, 1, 1, 1, 1, 1, 2, 3, 3, 3, 4, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 2, 2, 3, 3, 2, 3, 2, 1, 2, 2, 1, 2, 2, 2, 4, 1, 3, 2, 2, 2, 1, 2, 3, 2, 4, 2, 3, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 3, 1, 1, 2, 1, 1, 1, 1, 1, 3, 3, 3, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 3, 4, 3, 2, 3, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 4, 5, 4, 5, 5, 5, 5, 5, 6, 5, 6, 5, 4, 4, 3, 4, 4, 4, 6, 5, 6, 5, 5, 6, 5, 4, 6, 6, 5, 5, 5, 4, 6, 3, 5, 3, 5, 3, 2, 4, 4, 1, 3, 1, 2, 2, 2, 2, 3, 2, 3, 3, 2, 3, 3, 1, 4, 2, 3, 2, 2, 1, 2, 2, 2, 2, 3, 3, 2, 3, 3, 2, 3, 2, 3, 1, 3, 3, 2, 3, 2, 3, 2, 3, 2, 2, 3, 3, 2, 3, 2, 3, 2, 2, 3, 2, 4, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 3, 2, 3, 3, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 3, 2, 1, 2, 2, 2, 1, 3, 2, 3, 1, 3, 2, 3, 2, 4, 1, 2, 2, 2, 4, 1, 3, 3, 3, 2, 3, 3, 2, 3, 1, 3, 2, 2, 2, 3, 1, 3, 4, 4, 1, 5, 4, 4, 3, 4, 2, 5, 5, 4, 5, 4, 3, 3, 1, 4, 5, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 3, 1, 2, 1, 2, 3, 2, 2, 2, 2, 2, 2, 2, 1, 4, 4, 5, 4, 2, 3, 2, 2, 2, 3, 2, 3, 1, 1, 4, 5, 5, 6, 6, 6, 6, 2, 3, 3, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 2, 3, 2, 3, 3, 3, 2, 3, 4, 4, 4, 4, 5, 4, 1, 3, 2, 2, 3, 4, 3, 3, 4, 2, 1, 2, 2, 1, 3, 1, 2, 2, 1, 2, 1, 2, 1, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 4, 5, 4, 5, 3, 4, 3, 4, 4, 5, 4, 4, 5, 5, 4, 4, 3, 3, 3, 1, 3, 2, 3, 1, 4, 3, 3, 2, 3, 3, 2, 2, 2, 3, 1, 4, 3, 4, 4, 5, 5, 4, 2, 1, 3, 3, 4, 5, 3, 5, 2, 5, 4, 5, 4, 5, 2, 4, 2, 4, 1, 2, 3, 3, 1, 5, 5, 6, 6, 5, 4, 2, 4, 5, 7, 5, 4, 5, 7, 7, 7, 4, 6, 2, 1, 3, 3, 3, 3, 4, 2, 5, 3, 3, 2, 2, 3, 2, 3, 2, 1, 2, 6, 1, 5, 5, 5, 4, 4, 4, 4, 3, 5, 4, 2, 2, 2, 4, 2, 3, 6, 5, 5, 4, 1, 4, 5, 5, 3, 5, 4, 4, 5, 2, 5, 6, 3, 2, 4, 3, 5, 5, 5, 6, 4, 3, 5, 2, 2, 3, 5, 6, 5, 5, 6, 5, 2, 2, 3, 2, 2, 3, 4, 2, 4, 3, 4, 2, 3, 3, 1, 1, 2, 5, 5, 5, 4, 5, 4, 4, 4, 5, 5, 6, 3, 2, 5, 5, 5, 5, 5, 3, 3, 6, 3, 6, 5, 3, 6, 5, 5, 4, 2, 5, 3, 4, 4, 4, 2, 4, 4, 2, 2, 3, 3, 4, 2, 2, 4, 2, 4, 2, 3, 2, 2, 3, 3, 2, 2, 2, 1, 2, 3, 2, 3, 1, 3, 2, 2, 1, 2, 2, 2, 1, 3, 1, 2, 1, 3, 2, 1, 3, 3, 2, 2, 4, 2, 2, 2, 3, 2, 3, 2, 3, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 2, 3, 4, 3, 4, 3, 5, 3, 3, 4, 4, 4, 4, 3, 5, 5, 4, 5, 5, 4, 3, 5, 3, 4, 0, 2, 2, 3, 3, 3, 2, 4, 3, 3, 3, 1, 4, 4, 2, 4, 3, 2, 4, 3, 2, 5, 3, 2, 3, 4, 1, 3, 3, 2, 3, 4, 1, 2, 2, 5, 3, 3, 1, 4, 5, 2, 4, 5, 3, 5, 4, 5, 4, 2, 5, 3, 4, 2, 5, 4, 3, 5, 1, 5, 4, 4, 4, 4, 5, 2, 5, 5, 3, 4, 3, 3, 2, 3, 3, 3, 2, 3, 2, 2, 3, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 3, 1, 2, 2, 1, 3, 1, 3, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]).T

In [14]:
model = hmm.MultinomialHMM(n_components=5, n_iter=100)

In [15]:
model = model.fit(X)

In [16]:
model.transmat_

array([[9.41648462e-001, 2.78365202e-003, 2.11799951e-002,
        1.89941672e-022, 3.43878911e-002],
       [9.66895152e-003, 8.73068493e-001, 4.75644723e-002,
        6.96980829e-002, 4.84896506e-023],
       [1.65303814e-002, 2.34060278e-002, 9.59581300e-001,
        3.45769186e-005, 4.47713835e-004],
       [2.91826658e-039, 7.95727101e-002, 3.21695330e-003,
        9.17210337e-001, 4.95450666e-104],
       [4.22734102e-002, 3.37518862e-004, 6.01926217e-038,
        4.93907750e-050, 9.57389071e-001]])

In [17]:
model.emissionprob_

array([[4.04466302e-003, 1.49362071e-001, 4.75629493e-001,
        3.03179335e-001, 6.77844378e-002, 7.65060420e-013,
        7.97591595e-061, 1.62334457e-177],
       [2.27890952e-001, 7.72109048e-001, 8.33750764e-037,
        3.37233835e-122, 1.77183701e-222, 3.81563098e-216,
        6.56285745e-300, 0.00000000e+000],
       [1.71577435e-002, 9.64522073e-001, 1.83201831e-002,
        6.14634023e-069, 3.13258285e-157, 1.26278726e-198,
        1.65285754e-242, 0.00000000e+000],
       [9.61731956e-001, 3.82680442e-002, 3.80088184e-157,
        2.22329541e-322, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [6.67490191e-027, 1.65660874e-002, 4.33966155e-002,
        1.69422384e-001, 3.88202763e-001, 3.01170083e-001,
        6.48295275e-002, 1.64125386e-002]])

In [18]:
model.startprob_

array([0., 0., 0., 0., 1.])

In [19]:
model.monitor_.converged

True

In [20]:
model.monitor_

ConvergenceMonitor(history=[-5200.377058930067, -5200.367731837608], iter=69,
          n_iter=100, tol=0.01, verbose=False)

In [21]:
model.monitor_.history

deque([-5200.377058930067, -5200.367731837608])

In [22]:
state_sequence = model.predict(np.array([[1, 1, 0, 1, 0, 0]]).T)
print(state_sequence)

[4 1 1 1 3 3]


In [23]:
sq = model.predict(np.array([[0,0,1, 1 ,0, 2, 3, 0, 1, 2, 3]]).T)
print(sq)

[4 1 1 1 1 0 0 0 0 0 0]


In [24]:
prob_next_step = model.transmat_[state_sequence[-1], :]
print(prob_next_step)
next_state = np.argmax(prob_next_step)
print(next_state)

[2.91826658e-039 7.95727101e-002 3.21695330e-003 9.17210337e-001
 4.95450666e-104]
3


In [25]:
next_observation = np.argmax(model.emissionprob_[next_state])
print(next_observation)

0
